# 자료구조

## 튜플

* 튜플은 1차원의 고정된 크기를 가지는 '변경 불가능한' 순차 자료형

In [1]:
tup = 4, 5, 6
tup

(4, 5, 6)

In [2]:
nested_tup = (4, 5, 6), (7, 8)
nested_tup

((4, 5, 6), (7, 8))

In [5]:
list_to_tup = tuple([4, 0 ,2])
list_to_tup

(4, 0, 2)

In [6]:
tup = tuple('string')
tup

('s', 't', 'r', 'i', 'n', 'g')

In [7]:
tup[0]

's'

In [8]:
tup = 4, 5, (6,7)
a, b, (c, d) = tup

c

6

In [9]:
a, b = 1, 2
a

1

In [10]:
b, a = a, b

In [11]:
b

1

In [12]:
a

2

In [13]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

for a, b, c in seq :
    print('a={0}, b={1}, c={2}'.format(a, b, c))

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [14]:
!pip install pandas
!pip install numpy

In [15]:
import numpy as np
import pandas as pd

In [19]:
data = np.random.rand(2, 3)
data

array([[0.4891498 , 0.60903159, 0.77247277],
       [0.48527447, 0.86291809, 0.48187673]])

In [20]:
data.shape

(2, 3)

In [21]:
data.dtype

dtype('float64')

In [22]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [24]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [27]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr2

array([1, 2, 3])

In [30]:
arr1.dtype

dtype('float64')

In [33]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
arr_t = np.arange(15)
arr_t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr_tt = np.random.rand?

In [42]:
arr_tt = np.random.rand(3,2).reshape((1,6))
arr_tt

array([[0.1562845 , 0.41597536, 0.46860754, 0.7412146 , 0.09753354,
        0.92870141]])